from CateMate.models.breed import Breed
breeds = [
            Breed(name="Domestic Shorthair", category="domestic", hair_length="shorthair", is_official_breed=False),
            Breed( name="Domestic Mediumhair", category="domestic", hair_length="mediumhair", is_official_breed=False),
            Breed(name="Domestic Longhair", category="domestic", hair_length="longhair", is_official_breed=False),
            Breed(name="Mixed / Unknown", category="mixed", is_official_breed=False),
            Breed(name="European Shorthair", category="pedigree", hair_length="shorthair", registries="FIFe"),
            Breed(name="European Longhair", category="pedigree", hair_length="longhair", registries="FIFe"),
            Breed(name="Maine Coon", category="pedigree", hair_length="longhair", registries="FIFe,TICA,CFA"),
            Breed(name="British Shorthair", category="pedigree", hair_length="shorthair", registries="FIFe,TICA,CFA"),
            Breed(name="British Longhair", category="pedigree", hair_length="longhair", registries="TICA"),
            Breed(name="Norwegian Forest Cat", category="pedigree", hair_length="longhair", registries="FIFe,TICA"),
            Breed(name="Siberian", category="pedigree", hair_length="longhair", registries="FIFe,TICA"),
            Breed(name="Siamese", category="pedigree", hair_length="shorthair", registries="FIFe,TICA,CFA"),
            Breed(name="Oriental Shorthair", category="pedigree", hair_length="shorthair", registries="FIFe,TICA"),
            Breed(name="Oriental Longhair", category="pedigree", hair_length="longhair", registries="FIFe,TICA"),
            Breed(name="Persian", category="pedigree", hair_length="longhair", registries="FIFe,TICA,CFA"),
            Breed(name="Ragdoll", category="pedigree", hair_length="longhair", registries="TICA,CFA"),
            Breed(name="Bengal", category="pedigree", hair_length="shorthair", registries="TICA"),
            Breed(name="Birman", category="pedigree", hair_length="longhair", registries="FIFe,TICA"),
            Breed(name="Abyssinian", category="pedigree", hair_length="shorthair", registries="FIFe,TICA"),
            Breed(name="Somali", category="pedigree", hair_length="longhair", registries="FIFe,TICA"),
            Breed(name="Russian Blue", category="pedigree", hair_length="shorthair", registries="FIFe,TICA"),
            Breed(name="Chartreux", category="pedigree", hair_length="shorthair", registries="FIFe"),
            Breed(name="Turkish Angora", category="pedigree", hair_length="longhair", registries="FIFe,TICA"),
            Breed(name="Turkish Van", category="pedigree", hair_length="longhair", registries="FIFe,TICA"),
            Breed(name="Exotic Shorthair", category="pedigree", hair_length="shorthair", registries="CFA"),
            Breed(name="Scottish Fold", category="pedigree", hair_length="shorthair", registries="TICA"),
            Breed(name="Devon Rex", category="pedigree", hair_length="shorthair", registries="FIFe,TTICA"),
            Breed(name="Cornish Rex", category="pedigree", hair_length="shorthair", registries="FIFe,TTICA"),
            Breed(name="Sphynx", category="pedigree", hair_length="hairless", registries="FIFe,TTICA"),
            Breed(name="Peterbald", category="pedigree", hair_length="hairless", registries="TICA"),
            Breed(name="American Curl", category="pedigree", hair_length="shorthair", registries="TICA"),
            Breed(name="American Bobtail", category="pedigree", hair_length="shorthair", registries="TICA"),
            Breed(name="Japanese Bobtail", category="pedigree", hair_length="shorthair", registries="FIFe,TICA"),
            Breed(name="LaPerm", category="pedigree", hair_length="shorthair", registries="TICA"),
            Breed(name="Nebelung", category="pedigree", hair_length="longhair", registries="TICA"),
            Breed(name="Snowshoe", category="pedigree", hair_length="shorthair", registries="TICA"),
            Breed(name="Ocicat", category="pedigree", hair_length="shorthair", registries="FIFe,TICA"),
            Breed(name="Korat", category="pedigree", hair_length="shorthair", registries="FIFe,TICA"),
            Breed(name="Savannah", category="experimental", hair_length="shorthair", registries="TICA"),
            Breed(name="Toyger", category="experimental", hair_length="shorthair", registries="TICA"),
            Breed(name="Munchkin", category="experimental", hair_length="shorthair", registries="TICA"),
            Breed(name="Pixiebob", category="experimental", hair_length="shorthair", registries="TICA"),
            Breed(name="Other", category="other", is_official_breed=False),
]
